import { Router } from 'express';
import mongoose from 'mongoose';
import { Cinema, Task, Project, File, Avp } from './models.js';
import { requireValue, isAdmin } from './policy.js';
import { getItem, scope, validateUser, audit } from './resources.js';
import { upload } from './intake.js';
export const cinema=Router();
cinema.post('/cinemas',async(req,res)=> { const {title,description,department,task,rubric,reviewers}=req.body; const linkedTask=task ? await getItem(req,Task,task) : null; const project=req.body.project || linkedTask?.project; if(linkedTask && project) requireValue(String(linkedTask.project || '')===String(project),'Cinema project must match its task'); requireValue(typeof title==='string'&&title.trim()&&typeof rubric==='string'&&rubric.trim(),'Title and rubric responses required'); requireValue(department && department!=='*' && (isAdmin(req.user,department,project)||req.user.department===department),'Choose your department',403); requireValue(Array.isArray(reviewers)&&reviewers.length>0&&reviewers.length<=20,'Choose 1–20 reviewers'); for(const id of reviewers) { const reviewer=await validateUser(req,id); requireValue(reviewer.loginEnabled!==false,'Reviewer must have a login account'); } if(project) { const linkedProject=await getItem(req,Project,project); requireValue(linkedProject.department===department,'Department must match the linked project'); } const item=await Cinema.create({...scope(req),title,description,department,task:task||undefined,project:project||undefined,rubric,creator:req.user._id,number:`C-${new mongoose.Types.ObjectId()}`,status:'draft',steps:reviewers.map((reviewer,i)=>({reviewer,label:`Review ${i+1}`}))}); res.status(201).json(item); });
cinema.post('/cinemas/:id/reviewers', async (req,res) => {
 const c=await getItem(req,Cinema,req.params.id);
 requireValue(String(c.creator)===String(req.user._id)||isAdmin(req.user,c.department,c.project),'Not permitted',403);
 requireValue(c.status==='draft','Reviewers can only be set on a draft',409);
 requireValue(Array.isArray(req.body.reviewers)&&req.body.reviewers.length>0&&req.body.reviewers.length<=20,'Choose reviewers');
 for(const id of req.body.reviewers) { const user=await validateUser(req,id); requireValue(user.loginEnabled!==false,'Reviewer must have a login account'); }
 c.steps=req.body.reviewers.map((reviewer,i)=>({reviewer,label:`Review ${i+1}`}));
 await c.save(); res.json(c);
});
cinema.post('/cinemas/:id/submit',async(req,res)=> { const c=await getItem(req,Cinema,req.params.id); requireValue(String(c.creator)===String(req.user._id)||isAdmin(req.user,c.department,c.project),'Not permitted',403); requireValue(['draft','changes_requested'].includes(c.status),'Cannot submit this request',409); if(c.status==='changes_requested') { c.previousRounds.push({round:c.round,rubric:c.rubric,steps:c.steps.toObject()});c.round++;c.currentStep=0;c.steps.forEach(s=>s.status='pending'); } if(req.body.rubric) c.rubric=req.body.rubric; requireValue(c.steps.length>0,'Choose the approval reviewers before submitting'); c.status='in_review'; c.history.push({actor:req.user._id,event:'submitted',at:new Date()}); await c.save(); res.json(c); });
cinema.post('/cinemas/:id/decision',async(req,res)=> { const c=await getItem(req,Cinema,req.params.id); requireValue(c.status==='in_review','Request is not in review',409); const step=c.steps[c.currentStep]; requireValue(String(step.reviewer)===String(req.user._id)||isAdmin(req.user,c.department,c.project),'Only active reviewer or project admin may decide',403); requireValue(['approved','rejected','changes_requested','handoff'].includes(req.body.decision),'Invalid decision'); requireValue(typeof req.body.reason==='string'&&req.body.reason.trim(),'Reason required'); const history={actor:req.user._id,event:req.body.decision,reason:req.body.reason,at:new Date()}; if(req.body.decision==='handoff') { const user=await validateUser(req,req.body.reviewer); requireValue(user.loginEnabled!==false,'Reviewer must have a login account'); history.from=step.reviewer;history.to=user._id;step.reviewer=user._id; } else if(req.body.decision==='approved') { step.status='approved'; if(c.currentStep===c.steps.length-1) c.status='approved'; else c.currentStep++; } else { step.status='rejected';c.status=req.body.decision; } c.history.push(history); await c.save(); await audit(req,'cinemas',c._id,req.body.decision,history); res.json(c); });
cinema.post('/cinemas/:id/sow',upload.single('file'),async(req,res)=> { const c=await getItem(req,Cinema,req.params.id); requireValue(String(c.creator)===String(req.user._id)||isAdmin(req.user,c.department,c.project),'Not permitted',403); requireValue(['draft','changes_requested'].includes(c.status),'SOW changes require draft or changes-requested status',409); requireValue(req.file && /\.(pdf|docx|txt)$/i.test(req.file.originalname),'Upload PDF, DOCX or TXT'); const file=await File.create({...scope(req),uploader:req.user._id,cinema:c._id,filename:req.file.originalname,contentType:'application/octet-stream',bytes:req.file.buffer,version:await File.countDocuments({cinema:c._id})+1}); res.status(201).json({_id:file._id,filename:file.filename,version:file.version}); });
cinema.get('/cinemas/:id/files',async(req,res)=> { await getItem(req,Cinema,req.params.id); res.json(await File.find({...scope(req),cinema:req.params.id}).select('-bytes').sort({createdAt:-1})); });
cinema.get('/files/:id',async(req,res)=> { const file=await File.findOne({...scope(req),_id:req.params.id}).select('+bytes'); requireValue(file,'File not found',404); res.attachment(file.filename).type('application/octet-stream').send(file.bytes); });
cinema.get('/avp',async(req,res)=> { const items=await Avp.find(scope(req)).populate({path:'task',match:scope(req)}).lean(); res.json(items.filter(x=>x.task)); });
cinema.post('/avp',async(req,res)=> { const task=await getItem(req,Task,req.body.task); requireValue(isAdmin(req.user,task.department,task.project),'Admin required',403); if(req.body.cinema) await getItem(req,Cinema,req.body.cinema); const item=await Avp.create({...scope(req),task:task._id,cinema:req.body.cinema||undefined});res.status(201).json(item); });
cinema.patch('/avp/:id',async(req,res)=> { const item=await getItem(req,Avp,req.params.id);const task=await getItem(req,Task,item.task);requireValue(isAdmin(req.user,task.department,task.project)||String(task.owner)===String(req.user._id),'Owner or admin required',403);if(req.body.workflowStatus) item.workflowStatus=String(req.body.workflowStatus).slice(0,200);if(req.body.useCaseNeeded)item.useCaseNeeded=req.body.useCaseNeeded;if(req.body.note)item.notes.push({author:req.user._id,body:req.body.note});await item.save();res.json(item); });
